apiVersion: v1
kind: Service
metadata:
  name: service-b-service
  namespace: test-consul-namespace
  labels:
    app: service-b
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: service-b

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: test-consul-namespace
automountServiceAccountToken: true

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: service-b-defaults
  namespace: test-consul-namespace
spec:
  protocol: "http"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: test-consul-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
      annotations:
        consul.hashicorp.com/connect-service: 'service-b'
    spec:
      serviceAccountName: service-b
      containers:
        - name: service-b
          imagePullPolicy: Always
          image: jorourke/python-flask:latest
          command: [ "uvicorn", "src.b.app:app", "--host", "0.0.0.0", "--port", "8081" , "--log-config", "src/logging.yml" ]
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: names-config