apiVersion: v1
kind: Service
metadata:
  name: service-a-svc
  namespace: test-consul-namespace
  labels:
    app: service-a
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: service-a

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: test-consul-namespace
automountServiceAccountToken: true

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: service-a-defaults
  namespace: test-consul-namespace
spec:
  protocol: "http"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: test-consul-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        consul.hashicorp.com/connect-service: 'service-a'
    spec:
      serviceAccountName: service-a
      containers:
        - name: service-a
          imagePullPolicy: Always
          image: jorourke/python-flask:latest
          command: ["uvicorn", "src.a.app:app", "--host", "0.0.0.0", "--port", "8080"]
          ports:
            - containerPort: 8080